GET http://localhost:3000/api/users/me
Content-Type: text/plain
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJrbm9wbWlja2FlbCIsInVzZXJtYWlsIjoia25vcG1pY2thZWxAZ21haWwuY29tIiwicHJvZmlsZVBpY3R1cmUiOiJodHRwczovLzFkcnYubXMvaS9jLzRkZGY1MDA3NWU0ZGIwZTYvSVFTamcxNEZvUW9sUnJtLXR2SGU5XzB5QVhESWJ3enhEMGlmc25UTXhpZ19PTnM_d2lkdGg9MTAyNCIsImlhdCI6MTc0NjcyNzg5NCwiZXhwIjoxNzQ2NzMxNDk0fQ.SF25poGDr1o8HN_rG4T_QrZ_fBn5YBp4YNjGZkxHmN8