INSERT INTO sprites (hero_id, profile_picture, idle_sprite, attack_sprite, damage_received_sprite, celebration_sprite) VALUES
  (1,
  '/assets/images/slimes/red/profile_picture.png',
  '/assets/images/slimes/red/idle.png',
  '/assets/images/slimes/red/attack.png',
  '/assets/images/slimes/red/damage_received.png',
  '/assets/images/slimes/red/celebration.png'),
  (2,
  '/assets/images/slimes/green/profile_picture.png',
  '/assets/images/slimes/green/idle.png',
  '/assets/images/slimes/green/attack.png',
  '/assets/images/slimes/green/damage_received.png',
  '/assets/images/slimes/green/celebration.png'),
  (3,
  '/assets/images/slimes/purple/profile_picture.png',
  '/assets/images/slimes/purple/idle.png',
  '/assets/images/slimes/purple/attack.png',
  '/assets/images/slimes/purple/damage_received.png',
  '/assets/images/slimes/purple/celebration.png'),
  